import { createRoot, hydrateRoot } from "react-dom/client";
import App from "./App.tsx";
import "./index.css";

const rootEl = document.getElementById("root")!;

// Hydrate only when the HTML was generated by a real React prerenderer.
// The build-time SEO prerender writes a semantic crawler shell that does not
// match the React component tree, so clear it and mount fresh to avoid
// hydration mismatch errors.
if (rootEl.hasAttribute("data-react-snap")) {
  hydrateRoot(rootEl, <App />);
} else {
  if (rootEl.hasChildNodes()) rootEl.innerHTML = "";
  createRoot(rootEl).render(<App />);
}
